base_url = "https://spotlights.fossia.org"
title = "FOSSIA Spotlights"
description = "Shining spotlight on FOSSIA's first time contributors and mentors"
default_language = "en"
theme = 'zola-spotlights-theme'
compile_sass = false
build_search_index = true
output_dir = 'public'

taxonomies = [
    { name = "contributor", lang = "en", rss = true },
    { name = "mentor", lang = "en", rss = true }
]

[markdown]
highlight_code = false

[extra]
keywords = "contribution, mentoring, transcribeit"
menu_links = [
    { url = "$BASE_URL/", name = "About" },
    { url = "$BASE_URL/spotlight/contributor/", name = "Contributors" },
    { url = "$BASE_URL/spotlight/mentor/", name = "Mentors" },
    { url = "$BASE_URL/search/", name = "Search" },
    { url = "$BASE_URL/support/", name = "Support" },
]